### ISSUE TITLE
Question regarding the used license.

### ISSUE THREAD

**Issue by Masmblr** [GhostlyDark/SM64-Reloaded#1]
Hi! I would like to use this texture pack in one of my game levels (open source). Therefore, I would like to know which license the texture pack uses in order to provide the credits correctly. 
Best regards

**Comment by GhostlyDark** [comment]
The texture pack doesn't have a license, which is very much intentional. A lot of textures are based on the work of others which are listed on the linked website. I can't grant permission on behalf of any of the original authors.

That being said, a lot of assets are from [Render96HD,](https://github.com/pokeheadroom/RENDER96-HD-TEXTURE-PACK) which is licensed under GPL 3.0.

**Comment by Masmblr** [comment]
I understand. At this point, I have added an attribution notice in my readme that credits this project as the source. I hope that's acceptable.
